version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: mi_postgres
    environment:
      POSTGRES_DB: mi_base_datos
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña_segura
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario -d mi_base_datos"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
